// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkhsnxxfvtilercbeaez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raHNueHhmdnRpbGVyY2JlYWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNTM3NjgsImV4cCI6MjA2OTgyOTc2OH0.SngRI5YwkOM-uS5l6dwFRIpd7WNCIht40ogMMN_3t90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});